spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: technicalosksmith@gmail.com
    password: glqy nfmf sxin bjmi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
